### ISSUE TITLE
Unexpected Exit on Grep.

### ISSUE THREAD

**Issue by nyounker** [dthree/cash#56]
Initially I attempted a "grep" to search for a string inside a file using the -irl flags and found that the -L (lowercase) was not available but then tried the -n flag instead

Command executed

```
grep -irn "test" *
```
cash exits to windows prompt.

verification of error.

```
root:C/Users/Public/Documents$ root:C/Users/Public/Documents$ mkdir test1, test2, test3

root:C/Users/Public/Documents$ ls
desktop.ini My Music  My Pictures  My Videos  test1,  test2,  test3

root:C/Users/Public/Documents$ grep -irn "test" *
readline.js:925
            throw err;
            ^

SyntaxError: Invalid regular expression: /(*)/: Nothing to repeat
    at RegExp (native)
    at new RegExp (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\node_modules\babel-polyfill\node_mo
dules\core-js\modules\es6.regexp.constructor.js:26:11)
    at CommandInstance.exec (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal-grep\dist\grep.js:23:19)
    at CommandInstance.<anonymous> (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal-grep\dist\grep.js:
97:15)
    at EventEmitter.session.execCommandSet (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\sessi
on.js:476:20)
    at EventEmitter.vorpal._exec (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal.js:970:1
8)
    at EventEmitter.vorpal._execQueueItem (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal
.js:761:17)
    at EventEmitter.vorpal._queueHandler (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal.
js:745:10)
    at EventEmitter.vorpal.exec (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal.js:692:10
)
    at C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal.js:635:10
readline.js:925
            throw err;
            ^

SyntaxError: Invalid regular expression: /(*)/: Nothing to repeat
    at RegExp (native)
    at new RegExp (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\node_modules\babel-polyfill\node_mo
dules\core-js\modules\es6.regexp.constructor.js:26:11)
    at CommandInstance.exec (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal-grep\dist\grep.js:23:19)
    at CommandInstance.<anonymous> (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal-grep\dist\grep.js:
97:15)
    at EventEmitter.session.execCommandSet (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\sessi
on.js:476:20)
    at EventEmitter.vorpal._exec (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal.js:970:1
8)
    at EventEmitter.vorpal._execQueueItem (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal
.js:761:17)
    at EventEmitter.vorpal._queueHandler (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal.
js:745:10)
    at EventEmitter.vorpal.exec (C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal.js:692:10
)
    at C:\Users\$user\AppData\Roaming\npm\node_modules\cash-global\node_modules\cash\node_modules\vorpal\dist\vorpal.js:635:10
```

I don't know if this output will help and I'm not sure if there is an issue with an thirdparty .js, however I did test this exit with the following commands just to verify as well.. same result of exiting.

```
grep -irn "test*" *
grep -irn 'test*' *
grep -irn 'test' *
```

**Comment by dthree** [comment]
Thanks.

**Comment by ChatSim** [comment]
Do you want to save on roaming costs while travelling all around the world? Try ChatSim! ChatSim is the first SIM that lets you exchange unlimited instant messages and emoji, in more than 150 countries, using the most popular instant messaging apps, for only 10 euros/year, even without a WiFi connection. ChatSim can connect to the roaming operators, without charging in roaming. It can connect to more than 400 roaming operators. You can use: WhatsApp, Facebook Messenger, WeChat, Telegram, BBM, Line, Kik, Hike, Kakao, and QQi. ChatSim also works with 4G technology and has an automatic firewall that is able to block unwanted data traffic up to 90%. If you want to know more about ChatSim Unlimited, visit our website: chatsim.com/en

**Comment by legien** [comment]
I'll try to resolve this issue.

**Comment by nyounker** [comment]
Wow.  I didn't mean to make a spectacle of that error. I really apologize and thank you for legien stepping up.. after a month later I realized when m$ saw your project they got scared. You put some sense into the world of m$ . You and everybody participating. so they released bash/ or if you are from  windows \  mixed with ubuntu and unity. ...  There is a lot more that needs to be done with this project, only because everybody noticed the hard cut that m$ tried to apply. someone is scared about this project and that means WE should keep on working on it.

**Comment by nyounker** [comment]
I would recommend some additional help as this issue is still unresolved and I think it is an important issue to solve no matter the statement of releasing bash for ms, as is no one has solved this issue. seems like a power play to me to deviate from the good work that is going on here.

**Comment by legien** [comment]
The whole project was not updated for a month. I had no time recently. So, in you want to resolve this issue: Go ahead.

**Comment by dthree** [comment]
@nyounker thanks for your kind words :)

@legien sorry about that! I've been super busy in life recently and haven't had any time for OSS :(

Hoping that will change soon!
